Metric calculation replacements
publichealthengland/coronavirus-dashboard-frontend-server pull request #17
Opened 2020-11-25 13:33 UTC by Kegois

:)

2020-11-25 13:42 UTC, xenatisch requested changes
Minor changes needed.

2020-11-25 13:42 UTC, xenatisch commented on app/common/utils.py
> +    if data["changeDirection"] == "UP":
I think we can move this part to the template. It's only needed for that purpose and is redundant, specially because it is repeated under postcodes too.

2020-11-25 13:42 UTC, xenatisch commented on app/common/data/query_templates.py
> +        'changeDirection': c.${metric}Direction ?? null
I think we need the rolling sum in there too, don't we? It's the rolling sum that's displayed next to the percentage.

2020-11-25 13:42 UTC, xenatisch commented on app/common/utils.py
> +
Removing the trend calculation would let us remove this func and just use data!

2020-11-25 13:42 UTC, xenatisch commented on app/common/data/queries.py
> +def change_by_metric(timestamp, metric, ltla=False, postcode=None):
Can't we have this under `common` ?

2020-11-25 15:44 UTC, Kegois commented on app/common/utils.py
> +    if data["changeDirection"] == "UP":
moved to template with new template filter

2020-11-26 11:32 UTC, Kegois commented on app/common/data/query_templates.py
> +        'changeDirection': c.${metric}Direction ?? null
rolling sum is now included

2020-11-26 11:32 UTC, Kegois commented on app/common/data/queries.py
> +def change_by_metric(timestamp, metric, ltla=False, postcode=None):
moved get_change to common

2020-11-26 11:34 UTC, Kegois commented on app/common/utils.py
> +
trend calculation no longer here (now in template filter)

2020-11-26 15:05 UTC, xenatisch approved these changes

2020-11-26 15:10 UTC, merged